# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nicolas C. Jourdain
email: nicolas.jourdain@univ-grenoble-alpes.fr
description: > # this means to ignore newlines until "baseurl:"
  Physics of the climate system
baseurl: "" # the subpath of your site, e.g. /blog
url: http://nicojourdain.github.io/
github_username:  nicojourdain
twitter_username: nicojourd
header-img: img/baniere_3.jpg

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
